### ISSUE TITLE
Issue with Conquest

### ISSUE THREAD

**Issue by AugmentedAntics** [thane98/ignis#1]
I'd just like to know if Conquest is either bugged or unavailable. Just tried randomizing it, and when choosing to only randomize Conquest, the "Randomize" button is still greyed out. If I choose to randomize the other or all routes, I'm able to do so, but Conquest units don't swap join orders and receive appropriate weapons. On the flip side, their classes do still randomize.

**Comment by thane98** [comment]
Thanks for the report - this sounds like a bug. I will take a look at it tomorrow.

Just to be clear, which version of the game are you using? NA special edition, conquest, etc.

**Comment by AugmentedAntics** [comment]
NA Special Edition.

**Comment by thane98** [comment]
The button graying out was due to a UI bug - this is fixed now. Also fixed a bug related to join order swaps. Appears to be working on my end.

Sorry for the issues. Here's an updated build: [https://github.com/thane98/ignis/releases/download/pre-alpha/Ignis-Pre-Alpha.zip](https://github.com/thane98/ignis/releases/download/pre-alpha/Ignis-Pre-Alpha.zip)

**Comment by AugmentedAntics** [comment]
That much is now fine, but now this happens:
![1](https://user-images.githubusercontent.com/54159324/124204121-3b9b1900-da93-11eb-8418-4af8a5ebe419.png)
![2](https://user-images.githubusercontent.com/54159324/124204129-3e960980-da93-11eb-98f0-6baa20fb2782.png)

Looks like units are still having trouble rolling appropriate weapons.

Also, is stat redistribution supposed to give units such insane stats? I've already seen units capping stats even though they're not even high level.

**Comment by thane98** [comment]
- Will look into units not getting appropriate weapons.
- Redistribution is a pretty basic method for randomizing stats, so it could cause weird setups like having no luck but capped strength. But the screenshots look a little excessive, so I will double check the logic for this.

**Comment by thane98** [comment]
Build with weapons fix: [https://github.com/thane98/ignis/releases/download/pre-alpha/Ignis-Pre-Alpha-Weapons-Fix.zip](https://github.com/thane98/ignis/releases/download/pre-alpha/Ignis-Pre-Alpha-Weapons-Fix.zip)

In game results:
![silas](https://user-images.githubusercontent.com/26237510/124207640-ca5f6400-da9a-11eb-92a4-916ae0550159.png)
![flora](https://user-images.githubusercontent.com/26237510/124207646-cf241800-da9a-11eb-82d0-17c7bc30b369.png)

For stat redistribution, I lowered the amount of passes. This should lead to more reasonable stat spreads, but in the long run I probably need to add an algorithm that looks at the character + class stats a little more closely.

**Comment by AugmentedAntics** [comment]
Few more issues cropped up:
1. The Trade command is disabled on Chapter 4.
2. Ryoma's replacement may go off and attack other enemies on Chapter 5. I remember this happening a few times with the older randomizer, and it seemed most likely to happen if he was a flier.
3. Birthright units still have their classes randomized despite only selecting Conquest for randomization. Also, Ryoma keeps swapping in with Xander for some reason.
4. For some bizarre reason, after Chapter 6, a bunch of units just join at the castle.
5. On Mozu's paralogue, Corrin can't talk to Mozu's replacement (in this case, a pre-promoted Peri) for recruitment. This may or may not have to do with this same Peri being one in the bunch of units that joined at the castle. The output log does say she swapped with Anna, though.

**Comment by thane98** [comment]
Thanks for continuing to report this stuff.

Quick question - are you randomizing the same files repeatedly or is this using a clean output folder every time? I would recommend using a clean output folder since randomizing repeatedly can lead to weirdness. (I will update the readme and potentially add a warning about this on the UI).

1. I will take a look at this. Nothing in the randomizer should touch this, but evidently not.
2. Controlled by AI which the randomizer shouldn't edit. Worst case I can lock Ryoma's replacement to swordmaster for this chapter.
3. Sounds like I broke something, will fix.
4. Only addition should be Anna's replacement, but I think I see where the logic for adding her could break if the same ROM gets randomized over and over again.
5. I will look at why the talk event is broken.

**Comment by AugmentedAntics** [comment]
Not using a clean output folder, now that you mention it. I'll try again with a clean one and see what happens.

And as it turns out, 3 actually isn't a problem with the rando. I forgot that I initially randomized all the routes at first, then I randomized only Conquest and overwrote the files. The other points are active issues, though.

Edit: Yeah, a clean output folder fixed 3. Emptying the romfs folder in Citra also need to be done.
Edit 2: The Trade command works again.
Edit 3: Unfortunately, everything was going well until Chapter 10. The game freezes on the opening cutscene.

**Comment by thane98** [comment]
Sounds like progress at least? I will try to figure out what's going on with chapter 10.

From the points listed above I have fixes in mind for 2 and 4. I will test 5 as well.

**Comment by AugmentedAntics** [comment]
Removing B010.bin.lz from the Person folder temporarily fixes the crash.

**Comment by thane98** [comment]
Thanks for narrowing it down. Will keep it in mind for testing.

I've pushed a fix for more characters getting added to castle recruitment on reruns.

Also prevented reclassing, stat randomization, etc for Ryoma in chapter 5. This *should* help with the AI issue, but will have to see how well it works.

Edit: I'm not seeing this crash on Citra. It's possible that the game doesn't like a specific setup in this chapter. Do you still have the person file that caused the crash?

**Comment by AugmentedAntics** [comment]
So as it turns out, the rando didn't actually do anything with that file. What actually happened is that I edited Chapter 10 using Paragon months ago (I don't remember what I did that would change the Person file), and Paragon somehow broke it. However, the new joining units didn't have the right weapons except for Camilla's replacement (it's still Camilla, but a Dark Knight). I don't know if this requires a Person file for Chapter 10, because B010.bin.lz was not included in the output.

In case you still want to look at it, here it is:

[B010.bin.zip](https://github.com/thane98/ignis/files/6760051/B010.bin.zip)

**Comment by thane98** [comment]
I can still take a look at the file later.

Will look into why the Selena + Beruka replacements aren't getting correct weapons. This is a dispos issue, so the lack of person file is the randomizer working as intended.

Edit: Pushed a fix for Selena + Beruka replacements. Root cause was Ignis not recognizing these characters as replacements because they use route-specific (handover) pids.
